// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvelqzubzkcuqdtbiigw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2ZWxxenViemtjdXFkdGJpaWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNDg2OTIsImV4cCI6MjA3MzgyNDY5Mn0.dHFMU1rrIoDuSwhCRvn_LN14oxWV3e2yiULiLApnR_0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});